
package com.tapi.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IGreeting", targetNamespace = "http://facade.server.cxf.tapi.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGreeting {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayJson", targetNamespace = "http://facade.server.cxf.tapi.com/", className = "com.tapi.cxf.client.SayJson")
    @ResponseWrapper(localName = "sayJsonResponse", targetNamespace = "http://facade.server.cxf.tapi.com/", className = "com.tapi.cxf.client.SayJsonResponse")
    public String sayJson(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayXml", targetNamespace = "http://facade.server.cxf.tapi.com/", className = "com.tapi.cxf.client.SayXml")
    @ResponseWrapper(localName = "sayXmlResponse", targetNamespace = "http://facade.server.cxf.tapi.com/", className = "com.tapi.cxf.client.SayXmlResponse")
    public String sayXml(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
